apiVersion: batch/v1
kind: Job
metadata:
  name: iot-producer-job
spec:
  completions: 5         # Total number of Job instances (acts like replicas)
  parallelism: 5         # Number of Job instances to run in parallel
  template:
    metadata:
      labels:
        app: iot-producer
    spec:
      containers:
        - name: iot-producer
          image: 192.168.5.226:5000/producer-image:latest
          env:
            - name: KAFKA_BROKER_URL
              value: "kafka-service:9092"
            - name: PRODUCER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["python", "iot.py"]
          volumeMounts:
            - name: shared-volume
              mountPath: /app/output
      restartPolicy: Never
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc