# playbook_private_registry.yaml

- name: "Start Private Docker Registry Container"
  community.docker.docker_container:
    name: priplvate_registry
    image: registry:2
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"
  tags: registry