---
- name: Ensure firewalld is installed
  ansible.builtin.apt:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open Kafka port 9092 for inter-VM communication
  ansible.builtin.firewalld:
    rich_rule: 'rule family="ipv4" source address="192.168.5.0/24" port port="9092" protocol="tcp" accept'
    permanent: true
    immediate: yes
    state: enabled

- name: Open port 2181 for Zookeeper
  ansible.builtin.firewalld:
    rich_rule: 'rule family="ipv4" source address="192.168.5.0/24" port port="2181" protocol="tcp" accept'
    permanent: true
    immediate: yes
    state: enabled

- name: Open Producer/Consumer port 8080 for inter-VM communication using rich rules
  ansible.builtin.firewalld:
    rich_rule: 'rule family="ipv4" source address="192.168.5.0/24" port port="8080" protocol="tcp" accept'
    permanent: true
    immediate: yes
    state: enabled

- name: Open ML inference server port 5001 for inter-VM communication using rich rules
  ansible.builtin.firewalld:
    rich_rule: 'rule family="ipv4" source address="192.168.5.0/24" port port="5001" protocol="tcp" accept'
    permanent: true
    immediate: yes
    state: enabled

- name: Reload firewalld to apply changes
  ansible.builtin.service:
    name: firewalld
    state: reloaded