---
- name: Copy file with owner and permissions
  copy:
    src: /tmp/kafka_2.13-3.8.0.tgz
    dest: /tmp/kafka_2.13-3.8.0.tgz
    
- name: Ensure Kafka directory exists on VMs
  file:
    path: "/tmp/kafka"
    state: directory
    mode: '0755'

# check if tarball on VMs
- name: Verify Kafka tarball exists on VMs
  stat:
    path: /tmp/kafka_2.13-3.8.0.tgz
  register: kafka_tarball

- name: Output Kafka tarball existence result
  debug:
    msg: "Kafka tarball found: {{ kafka_tarball.stat.exists }}"

- name: Extract Kafka tarball
  unarchive:
    src: /tmp/kafka_2.13-3.8.0.tgz
    dest: /tmp/kafka
    remote_src: yes  # Indicates that the source file is already on the target

- name: Create Kafka logs directory
  file:
    path: /tmp/kafka_2.13-3.8.0/logs
    state: directory
    mode: '0755'

- name: Ensure Kafka is executable
  file:
    path: "/tmp/kafka/bin"
    mode: '0755'
    recurse: yes