apiVersion: v1
kind: PersistentVolume
metadata:
  name: elapsed-times-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"  # Replace this with your storage path
